baseURL = "https://www.kyrin.one/"
languageCode = "en"
title = "Kyrin Labs"
theme = "LoveIt"

defaultContentLanguage = "en"
hasCJKLanguage = true

paginate = 10

enableRobotsTXT = true
enableGitInfo = true

[params]
  description = "Kyrin Labs - Security Research & DLP Investigation"
  author = "Dalek"

[params.home]
  rss = 10

[params.social]
  GitHub = "https://github.com/freedalek"

[menu]

[[menu.main]]
  identifier = "cases"
  name = "Cases"
  url = "/0x00_cases/"
  weight = 1

[[menu.main]]
  identifier = "blogs"
  name = "Blogs"
  url = "/0x01_blogs/"
  weight = 2

[[menu.main]]
  identifier = "methodology"
  name = "Methodology"
  url = "/0x02_methodology/"
  weight = 3

[[menu.main]]
  identifier = "techshare"
  name = "TechShare"
  url = "/0x03_techshare/"
  weight = 4

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/0xff_about/"
  weight = 5

[taxonomies]
  tag = "tags"
  category = "categories"
